name: Build and Release Windows C++ Project

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build C++ Solution
      # Overriding the toolset to v143 forces VS 2022 to compile it without throwing an error
      run: msbuild offgit/OffGit.slnx /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

    - name: Stage Raw Executable
      shell: bash
      run: cp **/Release/OffGit.exe ./OffGit.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./OffGit.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
